# Generated by Django 3.2.5 on 2021-07-28 15:46

import catalog.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for presentation', primary_key=True, serialize=False, verbose_name='id')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('presentation_author', models.CharField(max_length=200, verbose_name='Author')),
                ('presentation_name', models.CharField(max_length=200, verbose_name='Presentation name')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200, verbose_name='Room')),
                ('places', models.IntegerField(default=30, verbose_name='Places')),
                ('free_places', models.IntegerField(default=30, verbose_name='Free places')),
                ('busy', models.BooleanField(default=False, verbose_name='Busy')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for schedule', primary_key=True, serialize=False, verbose_name='id')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('presentation', models.OneToOneField(null=True, on_delete=catalog.models.Presentation, to='catalog.presentation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.room')),
            ],
        ),
    ]
