# Generated by Django 3.2.5 on 2021-08-01 14:39

import catalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentation',
            options={'permissions': (('can_add_presentation', 'Add presentation'),)},
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for room', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='presentation',
            field=models.ForeignKey(null=True, on_delete=catalog.models.Presentation, to='catalog.presentation'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(on_delete=catalog.models.Room, to='catalog.room'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Presenter', 'Presenter'), ('Listener', 'Listener')], default='Listener', help_text='User role', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
