# Generated by Django 3.2.5 on 2021-08-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_schedule_listener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='listener',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Listener'),
        ),
    ]
